import type { Metadata } from 'next';
import '@styles/globals.css';
import { ReactNode } from 'react';
import { TitleBar } from '@components/index';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function MainLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <>
      <TitleBar />
      {children}
    </>
  );
}
