import SidebarRooms from '@components/SidebarRooms/SidebarRooms';
import { Splitter } from 'antd';
import type { Metadata } from 'next';
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function MainLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <>
      <Splitter lazy>
        <SidebarRooms />
        <Splitter.Panel>{children}</Splitter.Panel>
      </Splitter>
    </>
  );
}
