import type { Metadata } from 'next';
import '@styles/globals.css';
import { ReactNode } from 'react';
import { Open_Sans } from 'next/font/google';
import Providers from '@layouts/Providers/Providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
