import type { Metadata } from 'next';
import '@styles/globals.scss';
import { ReactNode } from 'react';
import { Open_Sans } from 'next/font/google';
import Providers from '@layouts/Providers/Providers';
import { TitleBar } from '@components/index';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <div className="wrapper">
          <Providers>
            <TitleBar />
            {children}
          </Providers>
        </div>
      </body>
    </html>
  );
}
